DROP TABLE IF EXISTS tagsharestable;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS soldshares;
DROP TABLE IF EXISTS shares;
DROP TABLE IF EXISTS portfolio;
DROP TABLE IF EXISTS users;


CREATE TABLE public.users
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" varchar NOT NULL,
    "hashed_password" varchar,
    "email" citext NOT NULL,
    "created" timestamp with time zone NOT NULL DEFAULT NOW(),
    "created_by_google" boolean NOT NULL,
    CONSTRAINT "users_pk" PRIMARY KEY ("_id") 
) WITH (
    OIDS=FALSE
);

CREATE TABLE public.portfolio
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" integer NOT NULL,
    "name" varchar NOT NULL,
    "created" timestamp with time zone NOT NULL DEFAULT NOW(),
    "last_accessed" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "portfolio_pk" PRIMARY KEY ("_id"),
    CONSTRAINT "fk_users" FOREIGN KEY (user_id) REFERENCES users(_id)
) WITH (
    OIDS=FALSE
);

CREATE TABLE public.shares
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "portfolio_id" integer NOT NULL,
    "ticker_name" varchar NOT NULL,
    "date_purchased" varchar NOT NULL,
    "price" integer NOT NULL,
    "number_shares" integer NOT NULL,
    CONSTRAINT "shares_pk" PRIMARY KEY ("_id"),
    CONSTRAINT "fk_portfolio" FOREIGN KEY (portfolio_id) REFERENCES portfolio(_id)
) WITH (
    OIDS=FALSE
);

CREATE TABLE public.soldshares
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "portfolio_id" integer NOT NULL,
    "shares_id" integer NOT NULL,
    "date_sold" varchar NOT NULL,
    "sell_price" integer NOT NULL,
    "number_shares" integer NOT NULL,
    CONSTRAINT "soldshares_pk" PRIMARY KEY ("_id"),
    CONSTRAINT "fk_portfolio" FOREIGN KEY (portfolio_id) REFERENCES portfolio(_id),
    CONSTRAINT "fk_shares" FOREIGN KEY (shares_id) REFERENCES shares(_id)
) WITH (
    OIDS=FALSE
);

CREATE TABLE public.tags
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tag_name" varchar NOT NULL,
    CONSTRAINT "tags_pk" PRIMARY KEY ("_id")
) WITH (
    OIDS=FALSE
);

CREATE TABLE public.tagsharestable
(
    "_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "tag_id" integer NOT NULL,
    "shares_id" integer NOT NULL,
    CONSTRAINT "sharestable_pk" PRIMARY KEY ("_id"),
    CONSTRAINT "fk_tag" FOREIGN KEY (tag_id) REFERENCES tags(_id),
    CONSTRAINT "fk_share" FOREIGN KEY (shares_id) REFERENCES shares(_id)
) WITH (
    OIDS=FALSE
)

-- INSERT INTO public.users VALUES (1, 'bonjay', null, 'bonjay@mail.com', current_timestamp, FALSE);
